name: mobile_football
description: Mobile application for football. Using the APIFootball service
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  hydrated_bloc: ^8.1.0
  json_annotation: ^4.4.0
  lottie: ^1.3.0
  animated_splash_screen: ^1.3.0
  path_provider: ^2.0.8
  jovial_svg: ^1.1.5
  cached_network_image: ^3.2.1
  football_repository:
    path: packages/football_repository
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/country-placeholder.png
    - assets/loaders/soccer-player.json